### ISSUE TITLE
Getting reasons for UnmetGuardConditions

### ISSUE THREAD

**Issue by KrauseT** [dotnet-state-machine/stateless#138] opened 2017-03-08 15:43 UTC
In my scenario, I would like to know the transitions from the statemachine that can not be executed in the current state. In addition, I would also like to get the description of the failed conditions (as a list) to show the user why he can not perform this transition. 
I can imagine that other users have similar scenarios.
Issue #55 has already covered something similar, but an exception with the description is only returned when the transition is executed.

Here is a small sample configuration:
```C#
sm.Configure(State.A)
  .PermitIf(Trigger.Request, State.B,
    new Tuple<Func<bool>, string>(() => false, "calculated vaule should be in range ...."),
    new Tuple<Func<bool>, string>(() => true, "do it"))
  .PermitIf(Trigger.Abort, State.C,
    new Tuple<Func<bool>, string>(() => true, "make it"))
  ;
```

Now the user can return all executable actions. But he has no clue why he can not perform the "_Request_" action (and no button on the surface is visible or this button is disabled).

With a few small adjustments, it is easy to provide this information with the Statemachine. I have already made these customizations locally and have also written UnitTests. The question is first of all whether the project is intended to make this information available.
If you are concerned about a condition that there are concrete indications, there is a risk for the application or security, it is free in the configuration of the condition to simply add no description for the error case.

If there is interest in the appropriate adjustments, I will gladly provide them in a branch.

**Comment by nblumhardt** [comment] 2017-03-09 04:23
Thanks for getting in touch!

If you're interested in submitting a PR and working through the process to get it merged, this sounds like a good improvement.

Could you share an example of the error messages before/after the proposed change?

**Comment by HenningNT** [comment] 2017-03-09 08:02
Is this functionality really needed? Will it clutter the API? I'm not sure, if we consider the Single Responsibility Principle, can this functionality be considered as part of the responsibility?
I think this feature is more a convenience, and it can be done by using a Trigger class object that contain the necessary information.

**Comment by nblumhardt** [comment] 2017-03-10 04:34
@HenningNT good questions; I think the before/after error messages would be a good illustration either way.

**Comment by KrauseT** [comment] 2017-03-10 08:15
Currently there are no error messages for transitions that can not be executed. Thus, it is not possible to display the error messages before expansion.
Currently there is only one public property for the transitions to be executed ("_PermittedTriggers_").
The adjustments would simply add another public feature ("_NotPermittedTriggers_"). This property returns a new property from the "CurrentRepresentation", similar to "_PermittedTriggers_". In the "_StateRepresentation_", only the calculation of the error messages (description of the _GuardClause_) is made for all non-executable transitions. This is similar to the "_PermittedTriggers_" property.

At this property of the statemachine you get a return type _Dictionary<TTrigger, HashSet<string>>_. This can also be generalized.

But now to the error messages after the changes. Let us take the following small sample configuration:
```C#
sm.Configure(State.A)
  .PermitIf(Trigger.X, State.B,
    new Tuple<Func<bool>, string>(() => false, "calculated vaule should be in range ...."),
    new Tuple<Func<bool>, string>(() => false, "calculated vaule should be in range ...."),
    new Tuple<Func<bool>, string>(() => false, "don't do it"),
    new Tuple<Func<bool>, string>(() => true, "make it")))
  .PermitIf(Trigger.Y State.C,
    new Tuple<Func<bool>, string>(() => true, "make it"))
  .PermitIf(Trigger.Z, State.B,
    new Tuple<Func<bool>, string>(() => false, "calculated vaule should be in range ...."),
    new Tuple<Func<bool>, string>(() => true, "make it")))
  ;
var notPermittedTrigger = sm.NotPermittedTriggers; //get all not executable Triggers
... // do you stuff with that information
```
The new property "_NotPermittedTriggers_" would provide a dictionary with two entries in which the transitions X and Z are available as keys.
Now I can get for example for the key X the error messages (here still as HashSet). This is exactly two error messages because the HashSet ensures that the error messages do not contain duplicates.

I hope I could explain the rough concept. As soon as I get to it, I will provide you with a PullRequest, so you can look at the changes and I also like to give wishes / hints to the adjustments. Specifically I think of the return type of the new property.

**Comment by nblumhardt** [comment] 2017-03-13 00:56
Ah, I see - thanks for the clarification @KrauseT. I originally inferred that you were talking about the error message that Stateless propagates when you attempt to fire a trigger that's not permitted. I see you're looking at this more from the exploratory angle; there would potentially be a change to the exception message in this situation, and an `out reason` parameter to `CanFire()` also.

There's definitely value in the concept, but I share some of @HenningNT's reservations about how much it might be put to use (weighed up against the API surface area and implementation/test effort).

Can we keep the ticket open and see whether anyone else comes looking for this? It'd help to have some more input, and maybe let the idea simmer for a little while. Does that work for you, @KrauseT ?

**Comment by KrauseT** [comment] 2017-04-10 08:18
I have the appropriate pull request available and for discussion. Perhaps there are other voices, which have the appropriate requirements or want to look at how they can insert themselves.
I hope for a lively discussion and hints on improvements.

**Comment by davisnw** [comment] 2017-07-26 04:03
I was looking for something similar - in my case I was using StateMachine.PermittedTriggers to drive the presentation of available actions to the user. That was all working great until I needed to add a guard condition. "Introspection" seems quite limited. For my use case all I would really need is the list of states that could be performed if all conditions were met - if I had that I could easily figure out my own messages to display - but without that I have to hard-code knowledge of the state transitions outside of the state machine which leads to duplication.

**Comment by lukaskostial** [comment] 2018-09-05 10:39
Hi @nblumhardt @HenningNT,

I'm not sure if this is a bug or by design so I'm rather asking here instead of opening a new issue:

With the configuration above, shouldn't `coll` in `OnUnhandledTrigger` contain UnmetGuardConditions ( in this case "calculated value should be in range ....") ?

```c#
sm.OnUnhandledTrigger((s, a, coll) => { ... });
```

It is due to the following code in StateRepresentation. `handlerResult` is `null` as `actual` already doesn't contain TriggerBehaviourResults with UnmetGuardConditions > 0 :

```c#
// Remove those that have unmet guard conditions
// Guard functions are executed here
var actual = possible
    .Select(h => new TriggerBehaviourResult(h, h.UnmetGuardConditions(args)))
    .Where(g => g.UnmetGuardConditions.Count == 0)
    .ToArray();

// Find a handler for the trigger
handlerResult = TryFindLocalHandlerResult(trigger, actual, r => !r.UnmetGuardConditions.Any())
    ?? TryFindLocalHandlerResult(trigger, actual, r => r.UnmetGuardConditions.Any());

if (handlerResult == null) return false;

return !handlerResult.UnmetGuardConditions.Any();
```

If this is intentional, could you please advise how to propagate the list of unmet guard descriptions to the caller ?

**Comment by rustybox** [comment] 2019-02-13 10:30
Related to #304, there was a regression that dropped the guard descriptions in the exception messages but resolved an issue elsewhere.

**Comment by mclift** [comment] 2024-01-15 13:25
Closing this issue as it appears to have been resolved as described above. Please let me know if it needs further work.

**Closed by mclift** 2024-01-15 13:25 UTC
