### ISSUE TITLE
Wrong behavior with FiringMode.Immediate in version 4.3.0

### ISSUE THREAD

**Issue by zedd137** [dotnet-state-machine/stateless#345] opened 2020-01-02 15:26 UTC
When a state machine is configured with FiringMode.Immediate and a trigger is fired in OnEntry() the resulting state is wrong.

Sample program:

```C#
using System;
using Stateless;

namespace TestStateless
{
    class Program
    {
        enum State
        {
            S1,
            S2,
            S3,
        }

        enum Trigger
        {
            T1,
        }

        private static StateMachine<State, Trigger> sm = new StateMachine<State, Trigger>(State.S1, FiringMode.Immediate);
        
        static void Main(string[] args)
        {
            sm.Configure(State.S1)
                .Permit(Trigger.T1, State.S2);

            sm.Configure(State.S2)
                .OnEntry(OnEntryS2)
                .Permit(Trigger.T1, State.S3);
            
            sm.Configure(State.S3)
                .OnEntry(OnEntryS3)
                .Permit(Trigger.T1, State.S1);

            System.Console.WriteLine("state before: " + sm.State);

            sm.Fire(Trigger.T1);

            System.Console.WriteLine("state after: " + sm.State);

            var k = Console.ReadKey();
        }

        private static void OnEntryS2()
        {
            System.Console.WriteLine("OnEntryS2()");
            sm.Fire(Trigger.T1);
        }

        private static void OnEntryS3()
        {
            System.Console.WriteLine("OnEntryS3()");
        }
    }
}
```

Program output with stateless 4.3.0: (wrong)
```
state before: S1
OnEntryS2()
OnEntryS3()
state after: S2
```

Program output with stateless 4.2.1: (as expected)
```
state before: S1
OnEntryS2()
OnEntryS3()
state after: S3
```

**Comment by HenningNT** [comment] 2020-02-04 15:44
I'm unable to reproduce with the latest in master, but it reproduces with the latest nuget package.
Maybe I should released the latest in master?

**Comment by HenningNT** [comment] 2020-02-04 15:46
Hang on, I found something. 4.3.0 has been released from dev, not master...
It's not working in dev.

**Comment by HenningNT** [comment] 2020-02-04 15:50
In hindsight, I should never have added the Immediate firing mode...

**Comment by HenningNT** [comment] 2020-02-06 08:40
Fixed in dev.
Will be included in next release.

**Closed by HenningNT** 2020-02-06 08:40 UTC
Labels: bug
