### ISSUE TITLE
.net core 3 support

### ISSUE THREAD

**Issue by j209** [dotnet-state-machine/stateless#324] opened 2019-07-11 08:47 UTC
Hi
Is there any plan for .net core 3.0 and above support?

**Comment by dodyg** [comment] 2019-07-12 14:38
I think stateless should just work for .NET Core 3.0 since it supports .NET Standard 1.0.

**Comment by dodyg** [comment] 2019-07-12 14:39
Related https://github.com/dotnet-state-machine/stateless/issues/314

**Comment by HenningNT** [comment] 2019-07-12 20:16
Do you mean specific .net-3-core-only features?

**Comment by vip32** [comment] 2019-11-11 10:18
here's a proper netstandard 2.0 only PR #334

**Comment by thompcd** [comment] 2020-02-08 05:02
examples confirmed to work using 3.1 as of 627304ec65fa6f546ec6c93a5299a5e20422bbf2

**Comment by HenningNT** [comment] 2020-02-08 21:54
Closing this, as I think it is covered in latest release.

**Closed by HenningNT** 2020-02-08 21:54 UTC
