### ISSUE TITLE
PermitDynamic does not handle reentry

### ISSUE THREAD

**Issue by tomthoros** [dotnet-state-machine/stateless#186] opened 2017-07-10 13:18 UTC
When using `PermitDynamic` with or without parameters it's impossible to stop it from reentering a state.

**Comment by HenningNT** [comment] 2017-07-20 11:41
I think we need a bit more information, could you provide an example / unit test that demonstrates this?

Does it always leave the state even when there is no valid destination state?

**Comment by tomthoros** [comment] 2017-07-28 07:31
> Does it always leave the state even when there is no valid destination state?

It correctly throws `No valid leaving transitions are permitted from state 'B' for trigger 'X'. Consider ignoring the trigger. ` exception if the StateSelector throws.

In the following program using `PermitDynamic` can reenter a state. But using `Permit` to try to reenter it throws an exception. I'm not sure what should happen actually, maybe this behavior is intended? But my first thought was that it wouldn't reenter a state.
The output of the following program is

```
Exit state A.
Enter state A.
Exit state A.
Enter state B.
Exit state B.
Enter state A.
```

```
    class Program
    {
        enum States 
        { 
            A,
            B,
        }
        enum Triggers
        {
            X,
            Y,
            Z
        }

        static States StateSelector(string parameter)
        {
            switch (parameter)
            {
                default: throw new ArgumentOutOfRangeException();
                case "A": return States.A;
                case "B": return States.B;
            }
        }

        static void Main(string[] args)
        {
            StateMachine<States, Triggers>.TriggerWithParameters<string> trig = new StateMachine<States,Triggers>.TriggerWithParameters<string>(Triggers.X);
            StateMachine<States, Triggers> sm = new StateMachine<States,Triggers>(States.A);
            sm.Configure(States.A)
                .OnEntry(() => { Debug.WriteLine("Enter state A."); })
                .OnExit(() => { Debug.WriteLine("Exit state A."); })
                .PermitDynamic(trig, StateSelector);
            sm.Configure(States.B)
                .OnEntry(() => { Debug.WriteLine("Enter state B."); })
                .OnExit(() => { Debug.WriteLine("Exit state B."); })
                //.Permit(Triggers.Y, States.B) // Illegal: Additional information: Permit() (and PermitIf()) require that the destination state is not equal to the source state. To accept a trigger without changing state, use either Ignore() or PermitReentry().
                .Permit(Triggers.Z, States.A);

            sm.Fire(trig, "A");
            sm.Fire(trig, "B");
            sm.Fire(Triggers.Z);

            Console.ReadLine();
        }
    }
```

**Comment by HenningNT** [comment] 2017-07-31 09:58
Well, we have PermitReentry to allow re-entrant triggers, but I haven't tried to use that with dynamic destinations. Perhaps you could use PermitDynamicIf, and prevent the transition to happen if it is re-entrant?

**Comment by tomthoros** [comment] 2017-07-31 10:13
The problem with `PermitDynamicIf` is that my trigger has a parameter which is not passed to the `guard` function.

**Comment by gerardog** [comment] 2018-04-24 15:46
+1 on this issue.
I have a dynamic transition that chooses between staying in current status "A" or transition to either "B" or "C". The problem is that if it stays in "A", the OnEntry is triggered again.

**Comment by HenningNT** [comment] 2018-04-25 11:16
Actually... this would be the expected behaviour...

![stateatoa](https://user-images.githubusercontent.com/13196280/39242459-5cd53d06-488a-11e8-9c0c-abcced41f4a9.png)

The state machine has to execute the Entry action of State.A.

**Comment by gerardog** [comment] 2018-04-27 20:50
Ok, then maybe this issue should be closed 'by-design' ?

**Comment by HenningNT** [comment] 2018-04-30 11:16
I'll close this... maybe we should have a FAQ section on the main page, because I think some of the questions are recurring.

**Closed by HenningNT** 2018-04-30 11:16 UTC
