### ISSUE TITLE
NullReferenceException bug introduced in commit c13e181b

### ISSUE THREAD

**Issue by jpnoir** [dotnet-state-machine/stateless#263] opened 2018-05-30 14:50 UTC
In StateRepresentation.Async.cs line 157 used to be:

                await (internalTransition?.ExecuteAsync(transition, args)).ConfigureAwait(false);

but the "?" was dropped in c13e181b so that it is now

                await (internalTransition.ExecuteAsync(transition, args)).ConfigureAwait(false);

If you have no transitions (e.g. the trigger is ignored) then the new implementation results in a NullReferenceException.

Repro attached.
[StatelessNullRefRepro.zip](https://github.com/dotnet-state-machine/stateless/files/2054632/StatelessNullRefRepro.zip)

**Comment by HenningNT** [comment] 2018-05-31 07:34
Thanks you for reporting this bug!
The problem comes from not actually ignoring the trigger,  so the method handling the fireing ends up processing it as it was configured as an internal action.

**Comment by HenningNT** [comment] 2018-05-31 08:18
The problem is present in the sync part as well, but does not throw an exception...

**Comment by HenningNT** [comment] 2018-05-31 12:04
I'm working on, but I need to check if the solution I've found also works with IgnoreIf.

**Comment by jpnoir** [comment] 2018-05-31 14:39
Great! And thanks. 

 

I have a (temporary) workaround so I won’t be impacted if you need to take your time to get it fixed.

**Comment by HenningNT** [comment] 2018-06-01 05:32
Fixed in v4.2

**Closed by HenningNT** 2018-06-01 05:32 UTC
Labels: bug
