### ISSUE TITLE
Latest prerelease v4.0.1-dev-00294 bug

### ISSUE THREAD

**Issue by IanElsinga** [dotnet-state-machine/stateless#249] opened 2018-04-26 23:04 UTC
I have been using Stateless Nuget stable version 4.0.0 but ran into the InternalTransitionIf bug #227  so I attempted to use the above Prerelease but that is throwing an exception with a simple async trigger fire that was never thrown before in an unrelated place in the state machine.   (Unrelated meaning it is transitioning to a state that does not use InternalTransitionIf)

`await sm.FireAsync(Trigger.Approved);`

Causes the following exception: 
```   
at Stateless.StateMachine`2.StateRepresentation.<ExecuteInternalActionsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireOneAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at LocalNamespaceNameRemoved.<OnDriverTransactionResponse>d__159.MoveNext() in …\DriverTransactionResponse.cs:line 66
```
Thanks, please let me know if it looks like this will take a while to fix and I'll rewrite to avoid InternalTransitionIf and go back to v4.0.0

**Comment by HenningNT** [comment] 2018-04-27 06:29
@IanElsinga would you mind taking a look at the 299 prerelease?
Could I salso ask you to post a test that demonstrate the problem?

**Comment by HenningNT** [comment] 2018-04-30 10:31
That's OK, I used the test in #227 and changed to FireAsync. It fails :-(
I'll take  a look...

**Comment by HenningNT** [comment] 2018-04-30 10:54
@IanElsinga could you check if you are using InternalTransitionIf instead of InternalTransitionAsyncIf?
If you are using the sync Version, and fireing async, then it will throw the null Reference exception because of `Handler` here is `InternalTriggerBehaviour.Sync`:

    internalTransition = result.Handler as InternalTriggerBehaviour.Async;

**Comment by IanElsinga** [comment] 2018-04-30 12:36
I had to stop using InternalTransitionIf since I had to go back to version 4.0.0 so I use neither at the moment.  But upgrading Stateless to 299 caused the FireAsync bug to appear even so.  The FireAsync bug is independent of InternalTransition(If/AsyncIf).

**Comment by HenningNT** [comment] 2018-04-30 12:47
Just another tidbit of info, the action handler have to be async as well. Below is the fully converted test from #227, and it passes with the latest in dev. I would really appreciate if you could supply a failing test 👍 

        [Fact]
        public async void TestInternalIf()
        {
            var machine = new StateMachine<State, Trigger>(State.A);

            machine.Configure(State.A)
                .InternalTransitionAsyncIf(
                    Trigger.X,
                    () => true,
                    async () =>
                    {
                        await Task.Run(() => Console.WriteLine("Should be here!"));
                    })
                .InternalTransitionAsyncIf(
                    Trigger.X,
                    () => false,
                    async () =>
                    {
                        await Task.Run(() => Console.WriteLine("Should NOT be here!"));
                    });

            await machine.FireAsync(Trigger.X);
        }

**Comment by IanElsinga** [comment] 2018-04-30 13:47
Hi @HenningNT, once again, the problem with the 299 bits has nothing to do with InternalTransition of any kind.  FireAsync fails for a state that does not use any of these InternalTransition variants.  If a new prelease is available since 299 I haven't tried that yet.   Note that InternalTransitionIf *does* work with 294 prerelease - that's not the issue.  If InternalTransitionIf is completely removed from the project, FireAsync still fails where it didn't in stable version 4.0.0.  Hope it's making sense!

**Comment by HenningNT** [comment] 2018-04-30 13:58
Sorry for being a bit slow today, the ref to #227 threw me off ;-)
Would you mind posting the code around DriverTransactionResponse.cs:line 66, since that is mentioned in the first post. With the Limited information at hand it's hard to know where to start looking.

**Comment by IanElsinga** [comment] 2018-05-04 19:26
More details for  you: 

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Stateless.StateMachine`2.StateRepresentation.<ExecuteInternalActionsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireOneAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireQueuedAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PowerTranzSDK.CardTerminals.Miura.PTZMiuraTerminal.<OnDriverTransactionResponse>d__138.MoveNext() in D:\GitHub\PowerTranz\PowerTranz-SDK-Win\PowerTranzSDK\PowerTranzSDK\StateMachine\DriverTransactionResponse.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

![image](https://user-images.githubusercontent.com/3292591/39648107-bcbaf8c6-4fb7-11e8-89b3-ed50974b1194.png)

**Comment by HenningNT** [comment] 2018-05-05 08:43
Would you mind posting the state machine configuration code that handles that trigger and the state that is the target of `Trigger.Approved`?

**Comment by HenningNT** [comment] 2018-05-07 06:27
@IanElsinga, would you mind testing the latest prerelease?
If that doesn't work I need a test case to fix this bug.

**Comment by IanElsinga** [comment] 2018-05-07 14:41
Hi @HenningNT, sorry it still doesn't work - same issue.  Note that it crashes *before* it gets to the code to be run after the state change.  For example, in this case the trigger changes to a state which has .OnEntryAsync(ProcessOnline) - it gets to .OnEntryAsync, but it crashes before even trying to run ProcessOnline. 

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Stateless
  StackTrace:
   at Stateless.StateMachine`2.StateRepresentation.<ExecuteInternalActionsAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireOneAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireQueuedAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PowerTranzSDK.CardTerminals.Miura.PTZMiuraTerminal.<OnDriverKeyboardResponse>d__137.MoveNext() in D:\GitHub\PowerTranz\PowerTranz-SDK-Win\PowerTranzSDK\PowerTranzSDK\StateMachine\DriverKeyboardResponse.cs:line 23

```

**Comment by HenningNT** [comment] 2018-05-07 19:53
At this point I need to see code that reproduces the problem. Either the state machine configuration, or a reduced state machine configuration in the form of a test. The exception message does not include enough information, so I need some more information.

**Comment by IanElsinga** [comment] 2018-05-08 16:17
Alright, I have a better idea of what is causing the problem.   To do this debugging session I used Stateless source code directly in my project from commit 6788ab5.

Take the following state: 

```
sm.Configure(State.Approved)
                .OnEntry(() => Prompt(DevicePrompt.DevicePromptApproved))
                .OnEntryAsync(OnFinalResult)
                .InternalTransition(Trigger.NotifyDidFinish, OnNotifyDidFinish)  //send response to POS
                .Permit(Trigger.RequestEmvTrxn, State.EmvTrxnRequested)
                .Permit(Trigger.StartNfcTrxn, State.DeviceNfcTrxnStarted)
                .Permit(Trigger.Disconnect, State.Disconnecting)
                .Permit(Trigger.Idle, State.Idle)
                .OnExit(ClearSdkState); //cleanup, prepare for next transaction
```
Now the end of OnFinalResult fires an internal trigger:  sm.Fire(Trigger.NotifyDidFinish).  There is no async code invoked in OnNotifyDidFinish.

I guess this has something to do with queuing, but I'm not sure how that all works.  

The sequence is: 

`await sm.FireAsync(Trigger.Approved);`

![image](https://user-images.githubusercontent.com/3292591/39768897-f1f2e4f2-52c0-11e8-95b9-1e87dbbb5e4a.png)
![image](https://user-images.githubusercontent.com/3292591/39768909-fa52a060-52c0-11e8-840a-ceb549a2c0ee.png)
![image](https://user-images.githubusercontent.com/3292591/39768970-2da194b2-52c1-11e8-9e14-869e3a9f7cb6.png)
![image](https://user-images.githubusercontent.com/3292591/39769005-466a2284-52c1-11e8-8aff-9329b079ac99.png)
![image](https://user-images.githubusercontent.com/3292591/39769050-6dfaf7f6-52c1-11e8-96cc-dc23866e625e.png)

So it winds up not being able to create an internalTransition as InternalTriggerBehavior.Async because that handler is not async.  internalTransition is thus null.

The Internal Transition is not intended to be async and is not indicated as such.

Hope that helps!

**Comment by HenningNT** [comment] 2018-05-08 20:07
Are we missing an async version of InternalTransition?

**Comment by IanElsinga** [comment] 2018-05-08 20:28
But the internal transition handler is not async!

**Comment by HenningNT** [comment] 2018-05-09 07:19
Maybe you could try wrapping the handler with Task.Run:

    InternalTransitionAsync(Trigger.X, async () => await Task.Run(() =>OnNotifyDidFinish ));

...or make `OnNotifyDidFinish` awaitable ?

**Comment by IanElsinga** [comment] 2018-05-09 17:40
Perhaps someone else can weigh in here, but I don't think artificially converting a non-async handler to async so that Stateless can use it is a viable option.  In my opinion Stateless should be able to work with both async and synchronous methods, and has up to this point in time.  Remember that version 4.0.0 does handle this correctly.   I feel that something has "broken".  If it is the decision to keep it this way, I would rather stick with version 4.0.0.   

If this has something to do with queuing/not queuing then by default it should work with queuing which in my understanding should be the default mode unless it is turned off.  So if this is indeed relevant, it should work unless perhaps I turn off queuing, which I can understand will complicate things.

**Comment by HenningNT** [comment] 2018-05-10 04:18
You have a very good point; if it was working in v4.0.0, then is should continue to work for all v4.x.x. I'll make sure it does 👍 

The problem is how the action handlers are handled internally, not with the queueing.

**Comment by HenningNT** [comment] 2018-05-10 04:41
@IanElsinga could you try PR #252, I think it should work.

**Comment by HenningNT** [comment] 2018-05-10 04:42
If it is successful then I'll merge the PR, and push out a v4.1 release.

**Comment by bddckr** [comment] 2018-05-28 16:14
I'm still seeing this in 4.1 but so far can't find a small example to show it off.

Removed all `Internal*` usages in my project and still am getting it, but if I follow the discussion correctly that's expected.

**Comment by IanElsinga** [comment] 2018-05-28 16:46
Interesting.  I wouldn't say it's expected - it should not generate that exception in my opinion.  The bug was closed before I had time to verify if the fix worked and I'm still using older version 4.0.0 due to this bug.    Hopefully it does get fixed or we'll be stuck with the old version...

**Comment by bddckr** [comment] 2018-05-28 16:49
Yep it is a regression coming from 4.0.0 for sure.

Still having a hard time finding what makes that happen but so far everything in my existing codebase that's using it is having that issue.

On the other hand it doesn't happen if I create simple new state machine...

**Comment by IanElsinga** [comment] 2018-05-28 17:14
Well, IF it is the same issue, see my long message above where I did a debug session.  It happens when you fire an async trigger with an async state entry (.OnEntryAsync) and then you call an internal transition that is NOT async and does not have an async handler.  For some reason it is expecting the InternalTransition to be async as well and thus fails to identify the non-async handler and assigns it to null which causes the null reference exception

**Comment by HenningNT** [comment] 2018-05-29 08:27
I added a test in [a committ](https://github.com/dotnet-state-machine/stateless/commit/8952f9d5a107cc57c4c73f4869e8f5f0201d6d28) that I thought demonstrated the problem, and then added code until the test didn't fail :-D

If the problem is still present, then could I ask you to please submit a failing test so that we can resolve this. I might have fixed a problem that wasn't a problem ;-)

**Comment by HenningNT** [comment] 2018-06-01 07:30
@bddckr I suspect your issue is related to #263, where the code would fall through to the internal transition handling. This should now be dealt with in the latest release. Could you please check with the latest?

**Comment by bddckr** [comment] 2018-06-01 08:16
@HenningNT That did the trick, thanks a lot!

**Comment by HenningNT** [comment] 2018-06-04 05:36
I'm closing this, I think the issue has been resolved. Let me know if it hasn't ;-)

**Closed by HenningNT** 2018-06-04 05:36 UTC
