### ISSUE TITLE
NullReferenceException in StateMachine`2.InternalFireQueued

### ISSUE THREAD

**Issue by varunpuranik** [dotnet-state-machine/stateless#311] opened 2019-03-27 00:38 UTC
When using the Stateless nuget version 4.2.1, we are sometimes seeing a NRE being thrown, with the callstack below. 

Call stack - 
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Stateless.StateMachine`2.InternalFireQueued(TTrigger trigger, Object[] args)
   at Stateless.StateMachine`2.InternalFire(TTrigger trigger, Object[] args)
   at Stateless.StateMachine`2.Fire(TTrigger trigger)`

The code that causes this to happen is this - 
this.machine.Fire(Trigger.CallSucceeded);

We do not see this issue with version 4.0.0. Could this be a regression? 
Or is that a red herring and it is because of the state machine being single-threaded? If that is the case, do we need to lock around each Fire call?

**Comment by HenningNT** [comment] 2019-04-10 06:26
The stateless library is not thread safe. If the problem goes away when using lock, then I suggest that you keep using locks ;-)

**Comment by HenningNT** [comment] 2020-03-28 22:16
I'm closing this as there is not much to go on, and it's been a year...

**Comment by afrostewie** [comment] 2021-01-15 06:28
> When using the Stateless nuget version 4.2.1, we are sometimes seeing a NRE being thrown, with the callstack below.
> 
> Call stack -
> `System.NullReferenceException: Object reference not set to an instance of an object.    at Stateless.StateMachine`2.InternalFireQueued(TTrigger trigger, Object[] args)
>    at Stateless.StateMachine`2.InternalFire(TTrigger trigger, Object[] args)    at Stateless.StateMachine`2.Fire(TTrigger trigger)`
> 
> The code that causes this to happen is this -
> this.machine.Fire(Trigger.CallSucceeded);
> 
> We do not see this issue with version 4.0.0. Could this be a regression?
> Or is that a red herring and it is because of the state machine being single-threaded? If that is the case, do we need to lock around each Fire call?

Hi, I know it has been 2 years, but I face the exact same crash with 5.1.8 (and also with previous releases).
Were you able to get to the bottom of it and solve this crash?

**Comment by HenningNT** [comment] 2021-01-15 16:38
I see, could you please provide a unit test that demonstrates the problem?

**Comment by afrostewie** [comment] 2021-01-15 17:43
My intention was not to reopen the issue.
I just wanted to contact @varunpuranik to get his idea\solution to the problem. (Maybe was it the threading\locking? I also use stateless in a multi threading application.)
Unfortunatelly it is quite sporadic and I wasn't able to reproduce it with a test.

**Comment by HenningNT** [comment] 2021-01-16 06:43
Ok, that is annoying, and without a way to reliable reproduce it is very hard to fix it.

**Closed** 2021-01-16 06:43 UTC

**Comment by afrostewie** [comment] 2021-01-18 05:42
Just a feedback for other, maybe it will help them: It seems the exception was caused by the multi-threading.
I managed to "lock around" every Fire(..) call so that parallel calls cannot be made from multiple threads. The exception has not appeared since then.
