### ISSUE TITLE
MissingManifestResourceException in build 2.5.79

### ISSUE THREAD

**Issue by paulanthonymorris** [dotnet-state-machine/stateless#71] opened 2016-07-21 17:27 UTC
I have a unit test that expects InvalidOperationException to throw when attempting to fire in a state where that trigger is not allowed. Was working fine until I updated from 2.5.62. The exception is throwing on the call to ResourceManager.GetString(name, cultureInfo).
 
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.Resources.MissingManifestResourceException): Unable to load resources for resource file "Stateless.StateMachineResources" in package "8c4135be-e11e-423c-829b-76933c7da27f".

**Comment by nblumhardt** [comment] 2016-07-21 21:50
Thanks for the report. This test case in `StateMachineFixture.cs` passes for me:

```csharp
        [Test]
        [ExpectedException(typeof(InvalidOperationException), 
            ExpectedMessage = "No valid leaving transitions are permitted from state 'A' for trigger 'X'. Consider ignoring the trigger.")]
        public void ExceptionThrownForInvalidTransition()
        {
            var sm = new StateMachine<State, Trigger>(State.A);
            sm.Fire(Trigger.X);
        }
```

Which .NET version are you running tests on?

Thanks!

**Comment by paulanthonymorris** [comment] 2016-07-22 12:10
I am referring to the Stateless library in PCL's with 4.5 and Profile 111 as well as in Xamarin Android 6.1 copying the dll locally in the Android project

**Comment by roncanepa** [comment] 2016-07-22 20:10
I believe I'm getting the same error, or at least a very similar one.  This is in a very tiny throw-away test project, so I could probably arrange to send it to you if it's helpful.

VS 2015 update 2
library project is .NET 4.5.2
test framework is nUnit 2.6.4
with the R# 2016.1 test runner


my test:
```
        [Test]
        public void CarShouldNot_Move_WhenParked()
        {
            var c = new Car();
            c.Move();
        }
```
and all the `move()` function does is call fire, which I have NOT configured with Permit() because I wanted to see it throw the exception:

```
 _machine.Fire(Event.StepOnGas);

```

Exception from test runner:

```
System.Resources.MissingManifestResourceException : Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Stateless.StateMachineResources.resources" was correctly embedded or linked into assembly "Stateless" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Stateless.StateMachine`2.DefaultUnhandledTriggerAction(TState state, TTrigger trigger)
   at Stateless.StateMachine`2.InternalFire(TTrigger trigger, Object[] args)
```

**Comment by nblumhardt** [comment] 2016-07-25 03:09
Thanks, I have tracked down the cause; in #70 the secondary (profile 259) CSPROJ file wildcard-includes the C# files but not the associated RESX. Testing a fix now.

**Comment by nblumhardt** [comment] 2016-07-25 03:20
I've pushed a fix that should be coming through CI soon. I'd dearly love to get this project over to `project.json` so that we can do away with the kludgy second-CSPROJ setup.

**Closed** 2016-07-25 03:20 UTC

**Comment by paulanthonymorris** [comment] 2016-07-26 14:44
@nblumhardt Thank you.
