### ISSUE TITLE
OnEntry behavour different: Unit test broken when updated to 4.3.0 from 4.2.1

### ISSUE THREAD

**Issue by shellinspector** [dotnet-state-machine/stateless#339] opened 2019-11-28 15:43 UTC
Hello, since updating to v4.3.0 something in the behaviour of the state machine has changed and a single unit test which worked with 4.2.1 stopped passing. Here is  what I am doing in my unit test:

1. Create a statemachine and put it in the state A
2. Fire an "Operational" trigger which should move it to state B and into substate C through initial transition of state B.
3. Before moving to C there is an _OnEntry_  for B  which calls a function that should Fire an "_Act_OperationalErrorTrigger" trigger and move the machine to state E (error) I provoke this behavour using **Moq** library using a callback like this:
`controller_mock.As<IMOTION_CONTROLLER>().Setup(m => m.SetExposureDefaultsAndStop()).Callback(() => machine.Fire(inputControls.TriggersCommon._Act_OperationalErrorTrigger, "Function", "Error on Exposure defaults")).Verifiable();`

_(note SetExposureDefaultsAndStop is the function that is called as part of B's OnEntry())_

What I am seeing instead is that I get an exception saying that :

> No valid leaving transitions are permitted from state 'E'(error) for trigger '_Act_OperationalErrorTrigger'. Consider ignoring the trigger.

What I also see upon debugging is that the OnEntry (or the contents of the OnEntry), seems to be called **twice** inside state B. And executing `SetExposureDefaultsAndStop()` function second time fires the same `_Act_OperationalErrorTrigger `another time but since the first firing of `_Act_OperationalErrorTrigger ` already moved state to E(error), the E(error) state is not prepared to treat the `_Act_OperationalErrorTrigger` trigger, casuing the above exception. 

I know I can work around by addin additional state configrations for the E(error) state, however it seems this will be patching unclear behavour, espectially since it was working just fine in version 4.2.1.  Could you please look into this or at least let me know if some behavouor change is expected by upgrading to 4.3.0 from 4.2.1.

**Comment by HenningNT** [comment] 2020-02-06 08:55
@shellinspector 
Would you mind posting a unit test that demonstrates this?
Some work has been done in dev branch that might resolve this, would you mind checking if this fixes your problem?

**Comment by HenningNT** [comment] 2020-02-06 08:57
@shellinspector Are you using the Immediate firing mode, or the Queued mode.

**Comment by HenningNT** [comment] 2020-02-06 09:10
I've found the problem, it's caused by calling Enter on the superstate when executing the initial transition.

**Comment by HenningNT** [comment] 2020-02-06 09:32
Closing this, the fix will be included in release 4.4.
If you have time, could you please check that it works for you?

**Closed by HenningNT** 2020-02-06 09:32 UTC
Labels: bug
