### ISSUE TITLE
InitialTransition in FiringMode.Immediate causes infinite loop

### ISSUE THREAD

**Issue by leeoades** [dotnet-state-machine/stateless#515] opened 2023-04-14 09:56 UTC
Adjusting the unit test in InitialTransitionFixture.cs to set the firing more to Immediate demonstrates this issue.

```
        [Fact]
        public void EntersSubState()
        {
            var sm = new StateMachine<State, Trigger>(State.A, FiringMode.Immediate);

            sm.Configure(State.A).Permit(Trigger.X, State.B);

            sm.Configure(State.B)
                .InitialTransition(State.C);

            sm.Configure(State.C)
                .SubstateOf(State.B);

            sm.Fire(Trigger.X);
            Assert.Equal(State.C, sm.State);
        }
```

**Comment by DeepakParamkusam** [comment] 2023-04-14 13:15
Appears to be duplicate of #439. I had found the [probable cause](https://github.com/dotnet-state-machine/stateless/issues/439#issuecomment-782944956), but couldn't fix it.

**Closed** 2023-04-14 13:55 UTC
