### ISSUE TITLE
guard function called twice?

### ISSUE THREAD

**Issue by Avareto** [dotnet-state-machine/stateless#228] opened 2018-02-10 14:35 UTC
Hi!
Can someone explain, why the guard function is called two times, when firing goNext? I was expecting it should be called only once. Here is my code (or have look at test function "WhenDiscriminatedByGuard_ChoosesPermitedTransition()" in StateMachineFixture.css, line 164 in the repro)
`enum S { State1, State2 };
enum T { goNext }

[TestMethod]
public void TestMethod1()
{
        var currentState = S.State1;
        var sm = new StateMachine<S, T>(() => currentState, s => currentState = s);
        sm.Configure(S.State1)
                .PermitIf(T.goNext, S.State2, () => guard());
        sm.Fire(T.goNext);
}
// called twice...???
public bool guard()
{
        return true;
}
`

**Comment by HenningNT** [comment] 2018-02-13 07:49
It shouldn't be called twice, which version are you using?

**Comment by Avareto** [comment] 2018-02-13 07:55
From Nuget: v4.0.0

**Comment by HenningNT** [comment] 2018-02-13 07:58
ok, that's a bit odd... I'll take a look.

**Comment by HenningNT** [comment] 2018-02-13 08:51
I had a look and that is actually by design!

There is a PermittedTriggers property, which will evaluate all guard functions to figure out which trigger can be executed. The state machine will use this when firing triggers.

**Comment by Avareto** [comment] 2018-02-13 09:16
Unfortunately, I have to do some expensive database operations to evaluate the guard status. This behavior will probably slow down my system significantly. 
Any way to get around it?

**Comment by Avareto** [comment] 2018-02-15 20:36
Sorry, but its much worse than I expected: When I use the same guard function in more than one PermitIf(…) statements, in my case in 3 state configurations, and I am triggering just one of those transitions, the guard function is called 6 times just for that transition. Can you please explain why it’s called 6 times and why this is by design? There should be a way to change the behavior? Otherwise the version of the library is unusable for me, which is unfortunate because I like it a lot?

**Comment by HenningNT** [comment] 2018-02-16 14:03
Well, saying by design was maybe a bit incorrect, I wasn't involved when that bit of code was written.

I think you have a few options:
1) Add a time stamp to the guard function, and cache the result. Invalidate the result if more than 260ms have passed since the last call to the guard.
2) Your state machine seems to depend on some external state. Model the dependency as another state machine. Then the new one can either be polled, or send messages to the first one about state changes.
3) Change stateless code so that the guard functions are called only once per trigger.

I'm hoping you'll do number 3 so everybody can enjoy the improvement 😁

**Comment by trgrote** [comment] 2018-03-09 19:05
This is happening in StateRepresentation::TryFindLocalHandler because the 'actual' TriggerBehaviorResults are kept as IEnumerables that's results aren't evaluated until TryFindLocalHandlerResult.  This is called twice and therefore causes the Results to be calculated twice, which is redundant. 

Solution is to just make that 'actual' an _actual_ collection so the guard clauses are evaluated instantly.

**Comment by trgrote** [comment] 2018-04-10 18:07
You can close this one. #235

**Closed** 2018-04-12 12:00 UTC
